export const appliances = [
  { id: 1, name: "Dishwasher" },
  { id: 2, name: "Washer" },
  { id: 3, name: "Freezer" },
  { id: 4, name: "Refrigerator" },
  { id: 5, name: "Drayer" },
  { id: 6, name: "Oven" },
  { id: 7, name: "Gas stove" },
  { id: 8, name: "Microwave" },
  { id: 9, name: "Trash compactor" },
  { id: 10, name: "Electrive stove" },
  { id: 11, name: "Garbage disposal" },
];
export const basement = [
  { id: 1, name: "Finished" },
  { id: 2, name: "Half-finished" },
  { id: 3, name: "Unfinished" },
  { id: 4, name: "None" },
];
export const flooring = [
  { id: 1, name: "Carpet" },
  { id: 2, name: "Marble" },
  { id: 3, name: "Tile" },
  { id: 4, name: "Hardwood" },
  { id: 5, name: "Resin / concrete" },
  { id: 6, name: "Real stone" },
  { id: 7, name: "Laminate" },
  { id: 8, name: "Softwood" },
  { id: 9, name: "Rubber" },
  { id: 10, name: "Linoleum / Vinyl" },
  { id: 11, name: "Other" },
];
export const rooms = [
  { id: 1, name: "Dining room" },
  { id: 2, name: "Office" },
  { id: 3, name: "Solarium / atrium" },
  { id: 4, name: "Family room" },
  { id: 5, name: "Gym" },
  { id: 6, name: "Workshop" },
  { id: 7, name: "Library" },
  { id: 8, name: "Walk-in closet(s)" },
  { id: 9, name: "Recreation room" },
  { id: 10, name: "Master bath" },
  { id: 11, name: "Sun room " },
  { id: 12, name: "Laundry room " },
  { id: 13, name: "Breakfast nook " },
  { id: 14, name: "Kids room " },
  { id: 15, name: "Pantry " },
];
export const indoorFeatures = [
  { id: 1, name: "Fireplace" },
  { id: 2, name: "Ceiling fans" },
  { id: 3, name: "Wet bar" },
  { id: 4, name: "Spiral Staircase" },
  { id: 5, name: "Intercom system " },
  { id: 6, name: "Attic" },
  { id: 7, name: "Jacuzzi tub" },
  { id: 8, name: "Security system" },
  { id: 9, name: "Skylights" },
  { id: 10, name: "Cable ready" },
  { id: 11, name: "Indoor swimming pool " },
  { id: 12, name: "Pool table " },
];
export const indoorAmenities = [
  { id: 1, name: "Controlled access" },
  { id: 2, name: "Gated entry" },
  { id: 3, name: "Sports court" },
  { id: 4, name: "Doorman" },
  { id: 5, name: "Tennis court " },
  { id: 6, name: "55+ community" },
  { id: 7, name: "Elevator" },
  { id: 8, name: "Fitness center" },
  { id: 9, name: "Assisted living community" },
  { id: 10, name: "Basketball court" },
  { id: 11, name: "Storage " },
  { id: 12, name: "Disabled access " },
];
export const architecture = [
  { id: 1, name: "Modern" },
  { id: 2, name: "Split-level" },
  { id: 3, name: "Colonial" },
  { id: 4, name: "Bungalow" },
  { id: 5, name: "Cape cod " },
  { id: 6, name: "French" },
  { id: 7, name: "Victorian" },
  { id: 8, name: "Craftsman" },
  { id: 9, name: "Tudor" },
  { id: 10, name: "Ranch" },
  { id: 11, name: "Spanish " },
  { id: 12, name: "Loft" },
];
export const exterior = [
  { id: 1, name: "Brick" },
  { id: 2, name: "Metal" },
  { id: 3, name: "Wood" },
  { id: 4, name: "Cement" },
  { id: 5, name: "Stone " },
  { id: 6, name: "Vinyl" },
  { id: 7, name: "Composition" },
  { id: 8, name: "Shingle" },
  { id: 9, name: "Other" },
];
export const outdooramenities = [
  { id: 1, name: "Balcony / patio" },
  { id: 2, name: "Waterfront" },
  { id: 3, name: "Sauna" },
  { id: 4, name: "Spa / hot tub" },
  { id: 5, name: "Greenhouse " },
  { id: 6, name: "Pool" },
  { id: 7, name: "Barbeque area" },
  { id: 8, name: "Fenced yard" },
  { id: 9, name: "Porch" },
  { id: 10, name: "Garden" },
  { id: 11, name: "Dock " },
  { id: 12, name: "Deck " },
  { id: 13, name: "RV parking" },
  { id: 14, name: "Sprinkler system" },
  { id: 15, name: "Lawn" },
];
export const roof = [
  { id: 1, name: "Metal" },
  { id: 2, name: "Built-up" },
  { id: 3, name: "Slate" },
  { id: 4, name: "Shingles" },
  { id: 5, name: "Composition " },
  { id: 6, name: "Tiles" },
  { id: 7, name: "Green garden" },
  { id: 8, name: "Wood" },
  { id: 9, name: "Asphalt" },
  { id: 10, name: "Solar panels" },
  { id: 11, name: "Rolled " },
  { id: 12, name: "Other" },
];
export const view = [
  { id: 1, name: "Ocean" },
  { id: 2, name: "Mountain" },
  { id: 3, name: "City" },
  { id: 4, name: "Water canal" },
  { id: 5, name: "Marina " },
  { id: 6, name: "Park" },
  { id: 7, name: "Territorial" },
  { id: 8, name: "Lake" },
  { id: 9, name: "Pond" },
];
export const cooling = [
  { id: 1, name: "Central" },
  { id: 2, name: "Geothermal" },
  { id: 3, name: "Solar" },
  { id: 4, name: "Evaporative" },
  { id: 5, name: "Refrigeration " },
  { id: 6, name: "Wall" },
  { id: 7, name: "Other" },
  { id: 8, name: "None" },
  { id: 9, name: "Other" },
];
export const heating = [
  { id: 1, name: "Central" },
  { id: 2, name: "Stove" },
  { id: 3, name: "Wall" },
  { id: 4, name: "Geothermal" },
  { id: 5, name: "Baseboard " },
  { id: 6, name: "Radiant" },
  { id: 7, name: "Solar" },
  { id: 8, name: "None" },
  { id: 9, name: "Other" },
];
export const heatingFuel = [
  { id: 1, name: "Electric" },
  { id: 2, name: "Propane" },
  { id: 3, name: "Oil" },
  { id: 4, name: "Gas" },
  { id: 5, name: "Solar " },
  { id: 6, name: "Cool" },
  { id: 7, name: "Wood" },
  { id: 8, name: "None" },
  { id: 9, name: "Other" },
];
export const parking = [
  { id: 1, name: "Attached" },
  { id: 2, name: "Assigned" },
  { id: 3, name: "Detached" },
  { id: 4, name: "Carport" },
  { id: 5, name: "On-street " },
  { id: 6, name: "None " },
];
